import { AvaClient } from '@ava/client-sdk'
import { daemonBaseUrl } from './daemonChatClient'

function client(): AvaClient {
  return new AvaClient({ baseUrl: daemonBaseUrl() })
}

export const daemonRuntimeClient = {
  loadSettings: () => client().loadSettings(),
  saveSettings: (data: unknown) => client().saveSettings(data),
  loadConversations: () => client().loadConversations(),
  saveConversations: (data: unknown) => client().saveConversations(data),
  classifyInput: (request: any) => client().classifyInput(request),
  dispatchInput: (request: any) => client().dispatchInput(request),
  startIntakeSession: (request: any) => client().startIntakeSession(request),
  replyIntakeSession: (request: any) => client().replyIntakeSession(request),
  analyzeTask: (request: any) => client().analyzeTask(request),
  planTask: (request: any) => client().planTask(request),
  getActiveTaskPlan: (request: any) => client().getActiveTaskPlan(request),
  setActiveTaskPlan: (request: any) => client().setActiveTaskPlan(request),
  clearActiveTaskPlan: (request: any) => client().clearActiveTaskPlan(request),
  dispatchCodeAgentTask: (request: any) => client().dispatchCodeAgentTask(request),
  listCodeAgentSessions: () => client().listCodeAgentSessions(),
  startCodeAgentSession: (sessionId: string) => client().startCodeAgentSession(sessionId),
  sendCodeAgentSessionMessage: (request: any) => client().sendCodeAgentSessionMessage(request),
  stopCodeAgentSession: (sessionId: string) => client().stopCodeAgentSession(sessionId),
  probeModels: (request: any) => client().probeModels(request),
  probeModelCapabilities: (request: any) => client().probeModelCapabilities(request),
  getProjectBrief: (request: any) => client().getProjectBrief(request),
  ensureProjectDocs: (request: any) => client().ensureProjectDocs(request),
  readWorkspaceText: (request: any) => client().readWorkspaceText(request),
  writeWorkspaceText: (request: any) => client().writeWorkspaceText(request),
  createWorkspaceDir: (request: any) => client().createWorkspaceDir(request),
  listWorkspaceDir: (request: any) => client().listWorkspaceDir(request),
  probeCodeAgents: () => client().probeCodeAgents<unknown[]>(),
  installCodeAgent: (agentId: string) => client().installCodeAgent(agentId),
  openPath: (request: any) => client().openPath(request),
  openTerminal: (request: any) => client().openTerminal(request),
  openVSCode: (request: any) => client().openVSCode(request),
  listMcpServers: () => client().listMcpServers<unknown[]>(),
  restartMcpServer: (serverId: string) => client().restartMcpServer(serverId),
  appendUnitTestResult: (entry: unknown) => client().appendUnitTestResult(entry),
  listToolAudit: (limit?: number) => client().listToolAudit<unknown[]>(limit),
  clearToolAudit: () => client().clearToolAudit(),
  listPlugins: (states: unknown) => client().listPlugins<unknown[]>(states),
  listPluginCommands: (states: unknown) => client().listPluginCommands<unknown[]>(states),
  getMarketplaceCatalog: (states: unknown, options: unknown) => client().getMarketplaceCatalog(states, options),
  installPluginFromGit: (url: string) => client().installPluginFromGit(url),
  installPluginFromFolder: (path: string) => client().installPluginFromFolder(path),
  installPluginFromZip: (path: string) => client().installPluginFromZip(path),
  uninstallPlugin: (pluginId: string) => client().uninstallPlugin(pluginId),
  updatePlugin: (pluginId: string) => client().updatePlugin(pluginId),
}
